# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

use_frameworks!
workspace 'DS_ExpertIOS'

target 'DS_ExpertIOS' do
  # Pods for DS_ExpertIOS

   target 'DS_ExpertIOSTests' do
      inherit! :search_paths
      # Pods for product testing, if any
   end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end

#target 'DsCoreIos' do
#  project '../Module/DsCoreIos/DsCoreIos'
#end