workflows:
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
          BUNDLE_ID: "com.aditya.DS-ExpertIOS"
          XCODE_WORKSPACE: "DS_ExpertIOS/DS_ExpertIOS.xcworkspace"
          XCODE_SCHEME: "DS_ExpertIOS"
    scripts:
      - name: Run tests
        script: |
          xcodebuild build \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -archive-flags="-destination 'generic/platform=iOS'" \
          clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=YES CODE_SIGNING_ALLOWED=NO
      - name: Build debug app
        script: |
          xcodebuild build \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -archive-flags="-destination 'generic/platform=iOS'" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=YES CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - nuradityo@gmail.com
        notify:
          success: true
          failure: true
