workflows:
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
          BUNDLE_ID: "com.aditya.DS-ExpertIOS"
          XCODE_WORKSPACE: "DS_ExpertIOS/DS_ExpertIOS.xcworkspace"
          XCODE_SCHEME: "DS_ExpertIOS"
    scripts:
      - name: Run tests
        script: |
          xcodebuild \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -archive-xcargs "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=<4N88KY43XS>" \
          -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=16.0' \
          clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO 
      - name: Build debug app
        script: |
          xcodebuild build \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -archive-xcargs "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=<4N88KY43XS>" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - nuradityo@gmail.com
        notify:
          success: true
          failure: true
