workflows:
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: latest
      cocoapods: default
      groups:
        - fastlane
      vars:
          BUNDLE_ID: "com.aditya.DS-ExpertIOS" # replace with your app bundle
          XCODE_WORKSPACE: "DS_ExpertIOS/DS_ExpertIOS.xcworkspace" # Isikan nama project Anda.
          XCODE_SCHEME: "DS_ExpertIOS" # Isikan nama scheme project Anda.
    scripts:
      - name: Run fastlane
        script: |
          cd DS_ExpertIOS
          bundle install
          bundle exec fastlane ios unit_test
      - name: Build debug app
        script: |
          xcodebuild build \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - nuradityo@gmail.com
        notify:
          success: true
          failure: true
