workflows:
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_WORKSPACE: "DS_ExpertIOS/DS_ExpertIOS.xcworkspace"
          XCODE_SCHEME: "DS_ExpertIOS"
    scripts:
      - name: Run tests
        script: |
          xcode-project run-tests \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
      - name: Build debug app
        script: |
          xcodebuild build \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - nuradityo@gmail.com
        notify:
          success: true
          failure: true
